POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test3@gmail.com",
    "password": "Aa0?aaaa"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "signchat.client1@gmail.com",
    "password": "Aa0?aaaa"
}

###

POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzMzNzgyODE3LCJleHAiOjE3MzYzNzQ4MTd9.idScFFR5wRhrPqnhxdC-EYsYNDKPUPLS7H0EnwDQ6SY"
}

###

POST http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzMzNTIwNjUzLCJleHAiOjE3MzM1MjI0NTN9.UNgEHHfvOidhqjd41hFDm5eNcgSrRby9Eh7kOz1VVR8
Content-Type: application/json

{
    "oldPassword": "Aa0?aaa0",
    "newPassword": "Aa0?aaa1"
}

###

POST http://localhost:3000/api/auth/reset-password/request
Content-Type: application/json

{
    "email": "daxnatale@gmail.com"
}

###

POST http://localhost:3000/api/auth/reset-password/verify-otp
Content-Type: application/json

{
    "email": "daxnatale@gmail.com",
    "otp": "434723"
}

###

POST http://localhost:3000/api/auth/reset-password/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImlhdCI6MTczNDg4ODc1MiwiZXhwIjoxNzM0ODg5MDUyfQ.J0swLITMGoNV_RWI3qjoDWUOSj7UXeeNPrUjA5gucbc
Content-Type: application/json

{
    "newPassword": "Aa!9ooop"
}

###

POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTczNDg4Njc1NCwiZXhwIjoxNzM0ODg4NTU0fQ.8JcW4msuLUzdGWs_Uer0x5zjT1DNP4iQXzbCPLwXXa4
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTczNDg4Njc1NCwiZXhwIjoxNzM3NDc4NzU0fQ.NSUjPDMFzIV6aLF16AJjlumxaJsp4HA46KpW-vbuPr8"
}

###

GET http://localhost:3000/api/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTczNDEyNTk0MiwiZXhwIjoxNzM0MTI3NzQyfQ.Drb-u_A5Pu-sOcqyEKZeULPF-QTBA0j1H9v30lJnQLM

###

GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzMzNzgyODE3LCJleHAiOjE3MzM3ODQ2MTd9.2pvYADKNRmHt73llfV-hBt75TPIzAtVGlvDkcVBr1sM

###

PUT http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzM3OTIzNTQ2LCJleHAiOjE3Mzc5MjUzNDZ9.G7cwYaClOonJ8XgXPZkBlYA7Xp2tjWAuAA6bg4TrHQg
Content-Type: application/json

{
    "firstName": "Vincenzo",
    "lastName": "Siciliano",
    "email": "test3@gmail.com",
    "phone": "3935883468"
}

###

DELETE http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM2OTUxMTIwLCJleHAiOjE3MzY5NTI5MjB9.P_TWr5nF5ylsAONrwSfcN7XBdSskRNQ9V14W2040WrU
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM2OTUxMTIwLCJleHAiOjE3Mzk1NDMxMjB9.9jkvaontOU3BSr8rceSkI7TmRRcoXtKcPHoRNAXGjVY"
}

###

GET http://localhost:3000/api/users/90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3NTUzMTUwLCJleHAiOjE3Mzc1NTQ5NTB9.AbtEZ-36hkG1h4XPoP6JmypKLOCG_uM7GXNsthjq0PM

###

GET http://localhost:3000/api/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM3OTIyMTIxLCJleHAiOjE3Mzc5MjM5MjF9.n0d-j4Vu4qe-CRpDB6GoMinYbym1zbHSVwt2xDt2QBk

###

GET http://localhost:3000/api/contacts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM3OTIyMTIxLCJleHAiOjE3Mzc5MjM5MjF9.n0d-j4Vu4qe-CRpDB6GoMinYbym1zbHSVwt2xDt2QBk

###

POST http://localhost:3000/api/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIxNzM0LCJleHAiOjE3Mzc5MjM1MzR9.RMdXwoyTmJxh4c1cZxD_I5PNAS5dGhwVK0F1zSC37Bc
Content-Type: application/json

{
    "firstName": "Zio Berardo",
    "lastName": null,
    "phone": "3394326360"
}

###

PUT http://localhost:3000/api/contacts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIxNzM0LCJleHAiOjE3Mzc5MjM1MzR9.RMdXwoyTmJxh4c1cZxD_I5PNAS5dGhwVK0F1zSC37Bc
Content-Type: application/json

{
    "firstName": "Mamma",
    "lastName": null,
    "phone": "3331509013"
}

###

DELETE http://localhost:3000/api/contacts/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIxNzM0LCJleHAiOjE3Mzc5MjM1MzR9.RMdXwoyTmJxh4c1cZxD_I5PNAS5dGhwVK0F1zSC37Bc

###

POST http://localhost:3000/api/contacts/sync
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIzNjc2LCJleHAiOjE3Mzc5MjU0NzZ9.YQswrPyOmx-6aonUpq30hQ1CJwPDWnSDJr690erA88U
Content-Type: application/json

{
    "newContacts": [
        {
            "firstName": "Zio Berardo",
            "lastName": null,
            "phone": "3394326360"
        }
    ],
    "updatedContacts": [],
    "deletedContacts": []
}

###

GET http://localhost:3000/api/calls?userId=4&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIzNjc2LCJleHAiOjE3Mzc5MjU0NzZ9.YQswrPyOmx-6aonUpq30hQ1CJwPDWnSDJr690erA88U

###

GET http://localhost:3000/api/calls/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIzNjc2LCJleHAiOjE3Mzc5MjU0NzZ9.YQswrPyOmx-6aonUpq30hQ1CJwPDWnSDJr690erA88U

###

DELETE http://localhost:3000/api/calls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM3OTIzNjc2LCJleHAiOjE3Mzc5MjU0NzZ9.YQswrPyOmx-6aonUpq30hQ1CJwPDWnSDJr690erA88U
Content-Type: application/json

{
    "ids": [21]
}

###

POST http://localhost:3000/api/tokens
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzM4ODgyNDc2LCJleHAiOjE3Mzg4ODQyNzZ9.e66bhyfamJxxb_m_0IykDttGW3EVAR4gTKUD6PaeFRM
Content-Type: application/json

{
    "expoToken": "ExponentPushToken[1acsasw_21321ASJADSAcsa]"
}

###

DELETE http://localhost:3000/api/tokens
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4ODgyNDYyLCJleHAiOjE3Mzg4ODQyNjJ9.SWNn4jY8Hj_WTOw5l2tdJ8vcy68Efl4Z2edYCjAIROU
Content-Type: application/json

{
    "expoToken": "ExponentPushToken[1234_abcd]"
}