POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "daxnatale@gmail.com",
    "password": "Aa0?aaaa"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "daxnatale@gmail.com",
    "password": "Aa!9ooop"
}

###

POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzMzNzgyODE3LCJleHAiOjE3MzYzNzQ4MTd9.idScFFR5wRhrPqnhxdC-EYsYNDKPUPLS7H0EnwDQ6SY"
}

###

POST http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzMzNTIwNjUzLCJleHAiOjE3MzM1MjI0NTN9.UNgEHHfvOidhqjd41hFDm5eNcgSrRby9Eh7kOz1VVR8
Content-Type: application/json

{
    "oldPassword": "Aa0?aaa0",
    "newPassword": "Aa0?aaa1"
}

###

POST http://localhost:3000/api/auth/reset-password/request
Content-Type: application/json

{
    "email": "daxnatale@gmail.com"
}

###

POST http://localhost:3000/api/auth/reset-password/verify-otp
Content-Type: application/json

{
    "email": "daxnatale@gmail.com",
    "otp": "434723"
}

###

POST http://localhost:3000/api/auth/reset-password/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImlhdCI6MTczNDg4ODc1MiwiZXhwIjoxNzM0ODg5MDUyfQ.J0swLITMGoNV_RWI3qjoDWUOSj7UXeeNPrUjA5gucbc
Content-Type: application/json

{
    "newPassword": "Aa!9ooop"
}

###

POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTczNDg4Njc1NCwiZXhwIjoxNzM0ODg4NTU0fQ.8JcW4msuLUzdGWs_Uer0x5zjT1DNP4iQXzbCPLwXXa4
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTczNDg4Njc1NCwiZXhwIjoxNzM3NDc4NzU0fQ.NSUjPDMFzIV6aLF16AJjlumxaJsp4HA46KpW-vbuPr8"
}

###

GET http://localhost:3000/api/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTczNDEyNTk0MiwiZXhwIjoxNzM0MTI3NzQyfQ.Drb-u_A5Pu-sOcqyEKZeULPF-QTBA0j1H9v30lJnQLM

###

GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzMzNzgyODE3LCJleHAiOjE3MzM3ODQ2MTd9.2pvYADKNRmHt73llfV-hBt75TPIzAtVGlvDkcVBr1sM

###

PUT http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzMzNzgyNjU0LCJleHAiOjE3MzM3ODQ0NTR9.HNmUxWGMt7O3JrwEDqOHH__8dQYvZDFN3Bpq6y0or8Y
Content-Type: application/json

{
    "firstName": "Davide",
    "lastName": "Natale",
    "email": "test@polito.it",
    "phone": "1234"
}

###

DELETE http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzMzNzgyODE3LCJleHAiOjE3MzM3ODQ2MTd9.2pvYADKNRmHt73llfV-hBt75TPIzAtVGlvDkcVBr1sM
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzMzNzgyODE3LCJleHAiOjE3MzYzNzQ4MTd9.idScFFR5wRhrPqnhxdC-EYsYNDKPUPLS7H0EnwDQ6SY"
}

###