POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test1@polito.it",
    "password": "Aa0?aaaa"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test1@polito.it",
    "password": "Aa0?aaaa"
}
###
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzMzNTA0MDc4LCJleHAiOjE3MzYwOTYwNzh9.OqiYo6JC8zFNIwbWqTreaNg2kNP9bFiLiDKSh23sGGw"
}
###
POST http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzMzNTIwNjUzLCJleHAiOjE3MzM1MjI0NTN9.UNgEHHfvOidhqjd41hFDm5eNcgSrRby9Eh7kOz1VVR8
Content-Type: application/json

{
    "oldPassword": "Aa0?aaa0",
    "newPassword": "Aa0?aaa1"
}
###
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNjU2MzgwLCJleHAiOjE3MzM2NTgxODB9.7Fr-GbnYmu__gWeb7Aw_yU8Y4quXoy1oqoE699N7rDE
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNjU2MzgwLCJleHAiOjE3MzYyNDgzODB9.xkreL_yUKVgtWcyEudUFzAMegY7LrodhFBGI_8fHxLk"
}
###
GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNjU2MzgwLCJleHAiOjE3MzM2NTgxODB9.7Fr-GbnYmu__gWeb7Aw_yU8Y4quXoy1oqoE699N7rDE
###
PUT http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNjU2MzgwLCJleHAiOjE3MzM2NTgxODB9.7Fr-GbnYmu__gWeb7Aw_yU8Y4quXoy1oqoE699N7rDE
Content-Type: application/json

{
    "firstName": "Davide2000",
    "lastName": "Natale",
    "email": "test2@gmail.com",
    "phone": "1234567890",
    "isDeaf": false
}
###
DELETE http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNjU2MzgwLCJleHAiOjE3MzM2NTgxODB9.7Fr-GbnYmu__gWeb7Aw_yU8Y4quXoy1oqoE699N7rDE
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzMzNTA0MDc4LCJleHAiOjE3MzYwOTYwNzh9.OqiYo6JC8zFNIwbWqTreaNg2kNP9bFiLiDKSh23sGGw"
}